### ISSUE TITLE
How to transition from Error::cause() to Error::source()

### ISSUE THREAD

**Issue by nils-ohlmeier** [nils-ohlmeier/rsdparsa#102]
Apparently https://doc.rust-lang.org/std/error/trait.Error.html#method.cause has been deprecated in Rust 1.33.0. This results in compiler warnings for Beta right now, but soon on on Release as well.

We are suppose to replace the .cause() calls with .source() calls, but since Error::source() only got added in Rust version 1.30.0 https://doc.rust-lang.org/std/error/trait.Error.html#method.source that would mean we would have to bump the minimum Rust version to 1.30.0 only to support that transition. That looks like a pretty high price to me.

It would be nice to stay backward compatible, but still be able to pay attention to compiler warnings as errors.

**Comment by nils-ohlmeier** [comment]
Added #105 as an intermediary solution for now (allowing deprecated functions in the tests which use cause()).

But still requiring Rust version 1.30 or greater only to get rid of deprecation warnings is big price to pay.

**Comment by na-g** [comment]
We could bump the minimum Rust version requirement to 1.30, add the `Error::source` implementation, and then file another bug to remove the deprecated interface at a specific time.

**Comment by nils-ohlmeier** [comment]
> We could file a bug to bump the minimum Rust version requirement to 1.30, add the `Error::source` implementation, and then file another bug to remove the deprecated interface at a specific time.

Right. That should ultimately be the plan. But bumping the minimum Rust version from 1.17 from 2017-04-27 to 1.30 released on 2018-10-25 (see https://github.com/rust-lang/rust/blob/master/RELEASES.md) is not only a big jump, but feels like requiring a pretty recent compiler version. I guess we will just leave as is with the deprecation for some more time and then eventually bump the min version to 1.30.

Maybe one interesting data point would be: which versions on rustc get shipped with recent Linux distros?
To get a feeling of what versions of rustc are distributed out their right now.

**Comment by na-g** [comment]
Ubuntu 19.04 ships with rustc 1.32.
Ubuntu 18.04 has rustc 1.31.
Debian stable has rustc **1.24**, testing is 1.32.
Fedora 28+ has rustc 1.33.
Arch Linux has rustc 1.34.

**Comment by na-g** [comment]
We have moved the minimum version to 1.30 with #113 via #114, so this work can proceed.
