### ISSUE TITLE
Make neccesary structs public, or surface the necessary information

### ISSUE THREAD

**Issue by Paul-E** [nils-ohlmeier/rsdparsa#11]
Eg [SdpAttribute's](https://github.com/nils-ohlmeier/rsdparsa/blob/master/src/attribute_type.rs#L388) members are private, and there is no way to access them, making the struct useless. Marking them as public causes the compiler to complain about leaking private types. Is the right solution to start marking things public until it compiles?

**Comment by nils-ohlmeier** [comment]
They all have been made public by now.
