### ISSUE TITLE
Tag and publish v0.2

### ISSUE THREAD

**Issue by na-g** [nils-ohlmeier/rsdparsa#128]
After having bumped the minimum Rust version to 1.30, we should tag the next release, v 0.2. This should include a note in the README.md or a CHANGELOG. Perhaps we should investigate what other crates do, and what crates.io will automatically grok.

**Comment by nils-ohlmeier** [comment]
Done :-)
https://github.com/nils-ohlmeier/rsdparsa/releases/tag/0.2.0
https://crates.io/crates/webrtc-sdp/0.2.0
