### ISSUE TITLE
Connection type should be allowed to exist in both the media and session sections simultaneously

### ISSUE THREAD

**Issue by na-g** [nils-ohlmeier/rsdparsa#130]
According to [RFC 4566](https://tools.ietf.org/html/rfc4566#page-14) this is allowed but we are treating this as a parsing error as of #111.

**Comment by nils-ohlmeier** [comment]
@na-g was this fixed through #132 or is there more left to do here?

**Comment by na-g** [comment]
Yes, this was fixed in #132.
