### ISSUE TITLE
Makes changes to SdpBandwidthType and SdpBandwidth

### ISSUE THREAD

**Issue by Paul-E** [nils-ohlmeier/rsdparsa#41]
The `Unknown` value in [`SdpBandwidthType`](https://github.com/nils-ohlmeier/rsdparsa/blob/19992cd897bf69782925e3d2f68ec769fc6a2dc1/src/lib.rs#L19) should carry a String if SdpBandwidthType it is only ever used in [`SdpBandwidth`](https://github.com/nils-ohlmeier/rsdparsa/blob/19992cd897bf69782925e3d2f68ec769fc6a2dc1/src/lib.rs#L27) with the `unknown_type` option set to the corresponding String. Then `unknown_type` in SdpBandwidth can be eliminated.

Alternatively, we can simplify down to one struct. Eg:

    pub enum SdpBandwidth {
        As(u64),
        Ct(u64),
        Tias(u64),
        Unknown(u64, String),
    }

or

    pub enum SdpBandwidth {
        As {bandwidth: u64},
        Ct {bandwidth: u64},
        Tias {bandwidth: u64},
        Unknown {bandwidth: u64, bandwidth_type: String},
    }

**Comment by nils-ohlmeier** [comment]
Makes sense to combine them into one. Probably result from implementing this in phases.

I would go with the tuples. I would only do `Unknown(String, u64)` as I assume in case of unknown you first want to look at the type.

**Comment by Paul-E** [comment]
One thing I find is that if the bandwidth comes first, then I can always grab the first element to get the bandwidth value, regardless of variant.

**Comment by nils-ohlmeier** [comment]
But the bandwidth numbers is completely meaningless without the type, because you don't even know if it's in bits, bytes, kilo-bytes or whatever other unit.
