### ISSUE TITLE
Check for extmap at session and media level

### ISSUE THREAD

**Issue by Paul-E** [nils-ohlmeier/rsdparsa#57]
The [Sipcc C++ glue](http://searchfox.org/mozilla-central/source/media/webrtc/signaling/src/sdp/SipccSdpAttributeList.cpp#881) has a check to ensure that there isn't an `extmap` attribute defined at both the media and session level. We should check this in the parser as well.

**Comment by nils-ohlmeier** [comment]
Fixed in #77
