### ISSUE TITLE
SdpAttributeRtpmap frequency is optional but clock rate in RFC 4566 is not marked as optional

### ISSUE THREAD

**Issue by Paul-E** [nils-ohlmeier/rsdparsa#66]
SdpAttributeRtpmap [frequency](https://github.com/nils-ohlmeier/rsdparsa/blob/master/src/attribute_type.rs#L252). RFC 4566 [section 6](https://tools.ietf.org/html/rfc4566#section-6).

**Comment by Paul-E** [comment]
[Permalink](https://github.com/nils-ohlmeier/rsdparsa/blob/a3c4b0a285c4658cf62c2d31e5c6232f8ced1c2a/src/attribute_type.rs#L259) for SdpAttributeRtpmap

**Comment by nils-ohlmeier** [comment]
Fixed
