### ISSUE TITLE
Parse into Fmtp more

### ISSUE THREAD

**Issue by Paul-E** [nils-ohlmeier/rsdparsa#67]
It looks like [sipcc](http://searchfox.org/mozilla-central/source/media/webrtc/signaling/src/sdp/SipccSdpAttributeList.cpp#682) does some format specific parsing of the Fmtp attribute. We probably want to do as much parsing in rust as possible, which means parsing Fmtp attributes in rsdparsa.

**Comment by nils-ohlmeier** [comment]
Closed through #86
