### ISSUE TITLE
Consider distribute the library as a crate

### ISSUE THREAD

**Issue by manifest** [nils-ohlmeier/rsdparsa#97]
Any plans on that?

**Comment by nils-ohlmeier** [comment]
I wasn't aware that anyone is interested in this yet :-)

Let me do one more sync between the Firefox code and this library and then I can go ahead and publish a crate.

**Comment by na-g** [comment]
@nils-ohlmeier, how would you feel about naming the crate something that made it obvious that it isn't a general purpose SDP parse, like web-rsdparsa or some such? It is just a thought.

**Comment by nils-ohlmeier** [comment]
That probably makes sense.

**Comment by nils-ohlmeier** [comment]
PR #99 prepares for publishing as 'webrtc_sdp'. Any thoughts on the name?

**Comment by nils-ohlmeier** [comment]
I actually tried it initially with -, but Rust was yelling at me that - is not allowed in crate names. So that's why I changed it to _.

**Comment by na-g** [comment]
@nils-ohlmeier, that `webrtc_sdp` sounds fine to me.

**Comment by manifest** [comment]
> I actually tried it initially with -, but Rust was yelling at me that - is not allowed in crate names. So that's why I changed it to _.

That's strange, for example `tower-web`:
https://github.com/carllerche/tower-web/blob/master/Cargo.toml#L2

**Comment by nils-ohlmeier** [comment]
Yes putting a name with - into the manifest was not causing problems. But when I then build the compiler complained about the extern statements like this https://github.com/nils-ohlmeier/rsdparsa/blob/master/src/bin/file_parser.rs#L6
Not allowing - in the name. Not sure what is up with that.

**Comment by nils-ohlmeier** [comment]
Looking at the error again is rather .... strange...

   Compiling webrtc-sdp v0.1.0 (/Users/nilsohlmeier/src/rsdparsa)
error: crate name using dashes are not valid in `extern crate` statements
 --> src/bin/file_parser.rs:6:14
  |
6 | extern crate webrtc-sdp;
  |              ^^^^^^^^^^ dash-separated idents are not valid
help: if the original crate name uses dashes you need to use underscores in the code
  |
6 | extern crate webrtc_sdp;
  |                    ^

error: aborting due to previous error

error: Could not compile `webrtc-sdp`.

**Comment by nils-ohlmeier** [comment]
This appears to give some context, but it's not pretty https://github.com/rust-lang/rfcs/blob/master/text/0940-hyphens-considered-harmful.md

**Comment by manifest** [comment]
You can simply use `extern webrtc_sdp;` for `webrtc-sdp` crate. Isn't it? That's what I thought. Hasn't released any crates yet.

**Comment by nils-ohlmeier** [comment]
Yes that appears to work to my surprise. I haven't released any crate either. So that's why I'm trying to not screw it up :)
I feel like combining webrtc_sdp and webrtc-sdp is not ideal. I'll probably poke a little more around before publishing.

**Comment by nils-ohlmeier** [comment]
Looks like I jumped the gun there... I can't publish a crate with * dependencies. Which then leads to reworking the clippy dependency, which then leads to tons of lingering clippy issues.

**Comment by nils-ohlmeier** [comment]
Done https://crates.io/crates/webrtc-sdp
